version: '2'

services:
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    php:
        build: php5-fpm
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ${WORKSPACE_APP_PATH}:/var/www/workspace

    db:
        user: "501:50"
        image: mysql
        container_name: db
        command: mysqld --sql_mode=""
        ports:
            - "3306:3306"
        volumes:
            - ${MYSQL_PATH}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: phpmyadmin
            volumes:
                - ${CONFIG_FILE}:/etc/phpmyadmin/config.user.inc.php
            ports:
                - "8080:80"
            links:
                - db

    varnish:
        image: biko2/docker-varnish
        container_name: varnish
        ports:
            - "8000:80"
        tty: true
        environment:
            VARNISH_BACKEND_PORT: 80
            VARNISH_BACKEND_IP: ${VARNISH_BACKEND_IP}
            VARNISH_PORT: 80
            VARNISH_MEMORY: 100M

